### ISSUE TITLE
format_rut not working

### ISSUE THREAD

**Issue by jcardenaslie** [gmgarciag/chile_rut#11]
Hola buenas! muchas gracias por crear el repo.

Encontre un error con el metodo de format_rut:

para el ejemplo que tienes en el repo no funciona, devuelve el siguiente error:

File "C:\ProgramData\Anaconda3\lib\site-packages\chile_rut\chile_rut.py", line 28, in format_rut
    for i in range(1, final+large/3):
TypeError: 'float' object cannot be interpreted as an integer

Saludos!

**Comment by gmgarciag** [comment]
Hola, Gracias por el reporte. 
Habia un error al ocupar python3 o superior.
Lo arreglé
